#!/bin/sh
#
# Produce a generated procmail.rc file.  Basically just a wrapper around
# m4, but it makes life easier.
#
# @(#) $Id: pgen,v 1.1 2001/06/16 20:27:25 dom Exp $
#

me=`basename $0`
prefix=/home/dom/work/pgen			# For testing.
M4DEFN="${prefix}/share/pgen/procmail-defn.m4"
MH=""

# We don't explicitly set the PATH on the assumption that the user may
# have m4 in some odd place in it.

usage () {
    echo "usage: $0 [-im] [-o outfile] procmail.m4" >&2
    exit 1
}

# Have a go at asking a few questions to generate a suitable start file
# for editing.
newprocmailrc () {
    dest="$1"
    # Set current PATH.
    # Ask where the mail should go.
    # Ask if $MAIL is ok as a default.
    # Try to figure out which sendmail we should be using.
}

while getopts "imo:" o
do
    case $o in
    i)	newprocmailrc $1 ;;
    m)  MH="-DMH-USER" ;;
    o)  exec >$OPTARG ;;
    *)  usage ;;
    esac
done
shift `expr $OPTIND - 1`

if [ $# != 1 ] ; then
    usage
fi

if [ ! -f "$1" ] ; then
    echo "$me: file $1 not found" >&2
fi
m4 $MH "$M4DEFN" "$1"

# vim: ai sw=4 et
