# This file is used when building mod_sed into apache.
#
# @(#) $Id: Makefile.tmpl,v 1.2 2001/06/15 07:24:18 dom Exp $

SRCS=		mod_sed.c compile.c main.c misc.c process.c

# Uncomment these bits to use standalone.  We have to use a slight
# modification of the standard apache depend target.

# INCDIR!=	apxs -q INCLUDEDIR
# INCLUDES=	-I$(INCDIR)
# OSDIR=		/usr/include
#
#depend:
#	cp Makefile.tmpl Makefile.tmpl.bak \
#	    && sed -ne '1,/^# DO NOT REMOVE/p' Makefile.tmpl > Makefile.new \
#	    && gcc -MM $(INCLUDES) $(CFLAGS) $(SRCS) >> Makefile.new \
#	    && sed -e '1,$$s: $(INCDIR)/: $$(INCDIR)/:g' \
#		   -e '1,$$s: $(OSDIR)/: $$(OSDIR)/:g' \
#		   -e '1,$$s: $(SRCS) : $$(SRCS) :g' Makefile.new \
#		> Makefile.tmpl \
#	    && rm Makefile.new

#Dependencies

$(OBJS) $(OBJS_PIC): Makefile

# DO NOT REMOVE
mod_sed.o: $(SRCS) $(INCDIR)/httpd.h \
 $(INCDIR)/ap_config.h \
 $(INCDIR)/ap_mmn.h \
 $(INCDIR)/ap_config_auto.h \
 $(INCDIR)/os.h $(INCDIR)/os-inline.c \
 $(INCDIR)/ap_ctype.h \
 $(INCDIR)/ap_alloc.h $(INCDIR)/buff.h \
 $(INCDIR)/ap.h $(INCDIR)/util_uri.h \
 $(INCDIR)/http_config.h \
 $(INCDIR)/http_core.h \
 $(INCDIR)/http_log.h \
 $(INCDIR)/http_main.h \
 $(INCDIR)/http_protocol.h \
 $(INCDIR)/http_request.h defs.h extern.h
