--- #YAML:1.0
name: Config-Setting
version: 0.03
author:
  - Dominic Mitchell, E<lt>cpan@happygiraffe.netE<gt>
abstract: Perl extension for configuration files.
license: bsd
requires:
  Test::More: 0
provides:
  Config::Setting:
    file: lib/Config/Setting.pm
    version: 0.03
  Config::Setting::Chunk:
    file: lib/Config/Setting/Chunk.pm
    version: 552
  Config::Setting::FileProvider:
    file: lib/Config/Setting/FileProvider.pm
    version: 555
  Config::Setting::IniParser:
    file: lib/Config/Setting/IniParser.pm
    version: 552
  Config::Setting::XMLParser:
    file: lib/Config/Setting/XMLParser.pm
    version: 552
generated_by: Module::Build version 0.2608
