.\" @(#) $Id: debug_client.1,v 1.1 2000/01/05 07:45:57 dom Exp $
.TH debug_client 1 "4 Jan 2000" "Local Software"
.SH NAME
debug_client \- connect to the spider daemon.
.SH SYNOPSIS
.B debug_client
.SH DESCRIPTION
.LP
The command
.B debug_client
connects to the
.BR spider (8)
daemon, by looking at the config file and using telnet to the correct
port.  It does require that one be familiar with the spider protocol.
.SH SEE ALSO
.BR spider (8).
.SH AUTHOR
.LP
Dominic Mitchell,
.I <dom@myrddin.demon.co.uk>
