.\" @(#) $Id: spider.8,v 1.2 2000/01/06 08:07:36 dom Exp $
.TH spider 1 "4 Jan 2000" "Local Software"
.SH NAME
spider \- bbs software
.SH SYNOPSIS
.B spider
[
.B -dn
] [
.B -c
.I conffile
]
.SH DESCRIPTION
.LP
.B spider
is the central daemon portion of the Spider BBS.  Normally, when
executed, it looks for a configuration file in
.IR !CONFIG! .
Also, spider will put itself into the background.
.LP
When started,
.B spider
will change into the spool directory specified in the configuration
file.  This defaults to 
.IR !PKGSPOOLDIR! .
.SH OPTIONS
.LP
There are several options available.
.TP
.B -c
Specify an alternate configuration file.
.TP
.B -d
Run in debug mode.  This will log each command sent to it.
.TP
.B -n
Do not fork into the background.  Reccommended for running under the
debugger.
.SH SEE ALSO
.BR kill_spider (8).
.SH AUTHOR
.LP
Dominic Mitchell,
.I <dom@myrddin.demon.co.uk>
